on:
  push:
    branches:
      - main

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: rust
          package-name: capillary
          changelog-types: >
            [
            {"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"ci","section":"CI","hidden":false},
            {"type":"build","section":"Build","hidden":false},
            {"type":"chore","section":"Miscellaneous","hidden":true},
            {"type":"docs","section":"Documentation","hidden":false},
            {"type":"style","section":"Code Style","hidden":true},
            {"type":"refactor","section":"Refactoring","hidden":true},
            {"type":"perf","section":"Performance","hidden":false},
            {"type":"test","section":"Testing","hidden":false}
            ]
